const express = require('express')
const router = express.Router()
const {signupHandler, loginHandler } = require("../controller/auth")
const {bookmovies} = require('../controller/home')
const {comingsoonMovies} = require('../controller/home')
const {choosesch} = require('../controller/choosesch')
const {displaySeats,getSeatAvailability} = require('../controller/seatsselect')
const {bill} = require('../controller/bill')
const {razor , payvalid} = require('../controller/razor')
const {insertSeats} = require('../controller/putseat')
const {ticketList} = require('../controller/ticklist')
const {getnews, getdesc} = require('../controller/news')
const {jwtverifyToken }= require('../middleware/jwtauth')


router.route('/').post(signupHandler)
router.route('/login').post(loginHandler)
router.route('/home').get(bookmovies)
router.route('/home/csoon').get(comingsoonMovies)
router.route('/choosesch').post(choosesch)
router.route('/seats').post(displaySeats)
router.route('/selectseats').post(insertSeats)
router.route('/seatavail').post(jwtverifyToken,getSeatAvailability)
router.route('/bill').post(bill)
router.route('/razorpay').post(jwtverifyToken,razor)
router.route('/payvalid').post(payvalid)
router.route('/ticketlist').post(ticketList)
router.route('/news').get(getnews)
router.route('/newsdesc').post(getdesc)

module.exports = router